import React, { createContext, useContext, useState, useEffect } from 'react';
import { authTranslations } from '../translations/auth';

export type Language = 'en' | 'es' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

// Translation data - merge main translations with auth translations
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.about': 'About',
    'nav.education': 'Education',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.language': 'Language',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.shipping': 'Shipping',
    'common.free': 'FREE',
    'common.explore': 'Explore',
    'common.optional': 'Optional',
    
    // Search
    'search.placeholder': 'Search products and pages...',
    'search.ariaLabel': 'Search MindVap website',
    'search.clear': 'Clear search',
    'search.searching': 'Searching...',
    'search.noResults': 'No results found',
    'search.tryDifferent': 'Try different keywords',
    'search.products': 'Products',
    'search.pages': 'Pages',
    'search.viewAll': 'View all results',
    'search.resultsFor': 'Results for',
    'search.result': 'result',
    'search.results': 'results',
    'search.found': 'found',
    
    // Registration
    'register.title': 'Create Your Account',
    'register.subtitle': 'Join MindVap for personalized wellness solutions',
    'register.pageTitle': 'Create Your Account',
    'register.pageSubtitle': 'Join MindVap for exclusive access to premium herbal wellness products',
    'register.email': 'Email Address',
    'register.emailPlaceholder': 'Enter your email address',
    'register.firstName': 'First Name',
    'register.firstNamePlaceholder': 'Enter your first name',
    'register.lastName': 'Last Name',
    'register.lastNamePlaceholder': 'Enter your last name',
    'register.dateOfBirth': 'Date of Birth',
    'register.age': 'Age',
    'register.phone': 'Phone Number',
    'register.phonePlaceholder': 'Enter your phone number',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Create a secure password',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPasswordPlaceholder': 'Confirm your password',
    'register.passwordStrength': 'Password Strength',
    'register.passwordMismatch': 'Passwords do not match',
    'register.invalidPhone': 'Please enter a valid phone number',
    'register.ageRequirement': 'You must be at least 21 years old',
    'register.termsRequired': 'You must accept the Terms of Service',
    'register.privacyRequired': 'You must accept the Privacy Policy',
    'register.dataProcessingRequired': 'You must accept data processing consent',
    'register.agreeTo': 'I agree to the',
    'register.termsOfService': 'Terms of Service',
    'register.privacyPolicy': 'Privacy Policy',
    'register.dataProcessingConsent': 'I consent to the processing of my personal data for account creation and communication purposes',
    'register.marketingConsent': 'I would like to receive marketing emails about new products and wellness tips',
    'register.createAccount': 'Create Account',
    'register.creating': 'Creating Account...',
    'register.alreadyHaveAccount': 'Already have an account?',
    'register.signIn': 'Sign In',
    'register.registrationSuccess': 'Registration successful!',
    'register.checkEmailVerification': 'Please check your email to verify your account',
    'register.redirecting': 'Redirecting to login...',
    'register.accountCreated': 'Account Created Successfully!',
    'register.registrationFailed': 'Registration failed. Please try again.',
    'register.whyJoin': 'Why Join MindVap?',
    'register.benefit1.title': 'Exclusive Products',
    'register.benefit1.desc': 'Access to premium, lab-tested herbal blends',
    'register.benefit2.title': 'Wellness Guidance',
    'register.benefit2.desc': 'Personalized recommendations based on your goals',
    'register.benefit3.title': 'Educational Content',
    'register.benefit3.desc': 'Expert insights on herbal wellness and usage',
    'register.benefit4.title': 'Member Benefits',
    'register.benefit4.desc': 'Special pricing and early access to new products',
    'register.securityNotice': 'Your Security is Our Priority',
    'register.securityDesc': 'We use industry-standard encryption and never share your personal information.',
    'register.ageVerification': 'Age Verification Required',
    'register.ageNotice': 'By registering, you certify that you are 21 years or older.',
    'register.termsAcceptance': 'By creating an account, you agree to our',
    
    // Home Page
    'home.hero.title': 'Natural Wellness Through Premium Herbal Vaping',
    'home.hero.subtitle': 'Discover evidence-based herbal blends crafted for mental wellness. Lab-tested, additive-free formulations designed for adults seeking natural anxiety relief, better sleep, and enhanced focus.',
    'home.hero.cta': 'Explore Our Collection',
    'home.trust.lab': 'Lab Tested',
    'home.trust.shipping': 'Free Shipping $50+',
    'home.trust.verified': 'Age 21+ Verified',
    'home.trust.coa': 'COA Available',
    'home.categories.title': 'Shop by Wellness Goal',
    'home.categories.subtitle': 'Explore our five carefully crafted categories, each designed to support specific mental wellness needs',
    'home.categories.anxiety': 'Anxiety Relief',
    'home.categories.sleep': 'Sleep Support',
    'home.categories.focus': 'Focus & Clarity',
    'home.categories.stress': 'Stress Relief',
    'home.categories.mood': 'Mood Support',
    'home.categories.keyHerbs': 'Key herbs:',
    'home.featured.title': 'Premium Wellness Collection',
    'home.featured.subtitle': 'Our most popular blends, chosen for their exceptional quality and customer satisfaction',
    'home.featured.cta': 'View All Products',
    'home.benefits.title': 'Evidence-Based Wellness',
    'home.benefits.ashwagandha.title': 'Ashwagandha for Stress',
    'home.benefits.ashwagandha.desc': 'Meta-analysis of RCTs shows large reductions in stress (SMD -1.75) and anxiety (SMD -1.55) with favorable effects at 300-600mg/day doses.',
    'home.benefits.chamomile.title': 'Chamomile for Anxiety',
    'home.benefits.chamomile.desc': 'Systematic review of 10 clinical trials concluded that chamomile improved anxiety in GAD, insomnia, and stress-related conditions.',
    'home.benefits.lavender.title': 'Lavender for Relaxation',
    'home.benefits.lavender.desc': 'Significant anxiety-reducing effects across 11 trials through inhalation aromatherapy, modulating limbic system activity.',
    'home.benefits.researched': 'Researched Herbs',
    'home.benefits.researched.desc': 'Each blend is formulated based on clinical research and traditional herbal knowledge',
    'home.howto.title': 'How to Use',
    'home.howto.subtitle': 'Simple steps for optimal herbal vaping experience',
    'home.howto.step1.title': 'Choose Your Blend',
    'home.howto.step1.desc': 'Select a blend based on your wellness goal - anxiety relief, sleep support, or mental clarity',
    'home.howto.step2.title': 'Set Temperature',
    'home.howto.step2.desc': 'Start at 160-177°C (320-350°F) for flavor, step up to 177-204°C (350-400°F) for balanced extraction',
    'home.howto.step3.title': 'Enjoy Mindfully',
    'home.howto.step3.desc': 'Session length: 5-15 minutes. Avoid temperatures above 221°C (430°F) to prevent combustion',
    'home.cta.title': 'Start Your Wellness Journey',
    'home.cta.subtitle': 'Explore our full collection of premium herbal blends designed for natural mental wellness',
    'home.cta.cta': 'Explore Our Collection',
    
    // Shop Page
    'shop.title': 'Our Products',
    'shop.subtitle': 'Discover our complete collection of premium herbal vaping blends',
    'shop.filter.all': 'All Products',
    'shop.filter.anxiety': 'Anxiety Relief',
    'shop.filter.sleep': 'Sleep Support',
    'shop.filter.focus': 'Focus & Clarity',
    'shop.filter.mood': 'Mood Support',
    'shop.filter.stress': 'Stress Relief',
    'shop.filter.category': 'Category',
    'shop.filter.priceRange': 'Price Range',
    'shop.filter.clearAll': 'Clear All Filters',
    'shop.filter.filters': 'Filters',
    'shop.filter.applyFilters': 'Apply Filters',
    'shop.filter.noProducts': 'No products found',
    'shop.filter.clearFilters': 'Clear filters',
    'shop.filter.tryAdjusting': 'Try adjusting your filters',
    'shop.productsAvailable': 'products available',
    'shop.onlyLeft': 'Only {count} left!',
    'shop.addToCart': 'Add to Cart',
    'shop.viewDetails': 'View Details',
    'shop.outOfStock': 'Out of Stock',
    'shop.inStock': 'In Stock',
    'shop.rating': 'Rating',
    'shop.reviews': 'reviews',
    
    // Product Detail
    'product.details': 'Product Details',
    'product.description': 'Description',
    'product.benefits': 'Benefits',
    'product.usage': 'Usage Instructions',
    'product.safety': 'Safety Information',
    'product.herbs': 'Herbal Blend',
    'product.temperature': 'Optimal Temperature',
    'product.category': 'Category',
    'product.stock': 'Stock Level',
    'product.addToCart': 'Add to Cart',
    'product.addedToCart': 'Added to Cart!',
    'product.goToCart': 'Go to Cart',
    'product.continueShopping': 'Continue Shopping',
    'product.notFound': 'Product not found',
    'product.returnToShop': 'Return to Shop',
    'product.tab.overview': 'Overview',
    'product.tab.benefits': 'Benefits',
    'product.tab.usage': 'Usage Guidelines',
    'product.tab.safety': 'Safety & Contraindications',
    'product.productDescription': 'Product Description',
    'product.keyHerbs': 'Key Herbs',
    'product.temperatureRange': 'Temperature Range',
    'product.evidenceBasedBenefits': 'Evidence-Based Benefits',
    'product.usageGuidelines': 'Usage Guidelines',
    'product.safetyContraindications': 'Safety & Contraindications',
    'product.quantity': 'Quantity',
    'product.wishlist': 'Wishlist',
    'product.share': 'Share',
    'product.labTested': 'Lab Tested with COA',
    'product.freeShipping': 'Free Shipping on Orders $50+',
    'product.easyReturns': 'Easy 30-Day Returns',
    'product.ageVerified': 'Age 21+ Verified',
    'product.onlyLeft': 'Only {count} left in stock!',
    'product.inStock': 'In Stock',
    
    // Cart Page
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your Cart is Empty',
    'cart.empty.desc': 'Discover our premium herbal blends and add them to your cart.',
    'cart.browseProducts': 'Browse Products',
    'cart.orderSummary': 'Order Summary',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.freeShippingThreshold': 'Add',
    'cart.freeShippingMessage': 'more for free shipping!',
    'cart.removeItem': 'Remove item',
    'cart.updateQuantity': 'Update quantity',
    
    // Checkout Page
    'checkout.title': 'Secure Checkout',
    'checkout.contactInfo': 'Contact Information',
    'checkout.email': 'Email Address',
    'checkout.shippingAddress': 'Shipping Address',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.address': 'Street Address',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.zipCode': 'ZIP Code',
    'checkout.country': 'Country',
    'checkout.paymentInfo': 'Payment Information',
    'checkout.payment.desc': 'Complete the information above, then click the button below to proceed to payment.',
    'checkout.ageVerification': 'Age Verification',
    'checkout.ageVerification.text': 'I certify that I am 21 years of age or older. I understand that these products are not intended to diagnose, treat, cure, or prevent any disease and have not been evaluated by the FDA.',
    'checkout.continueToPayment': 'Continue to Payment',
    'checkout.preparingPayment': 'Preparing Payment...',
    'checkout.completePurchase': 'Complete Secure Purchase',
    'checkout.processingPayment': 'Processing Payment...',
    'checkout.securePayment': 'Secure SSL encrypted payment',
    'checkout.orderComplete': 'Order Complete!',
    'checkout.orderComplete.desc': 'Thank you for your purchase. You\'ll receive a confirmation email shortly with tracking information.',
    'checkout.orderSummary': 'Order Summary',
    'checkout.redirecting': 'Redirecting to homepage...',
    
    // About Page
    'about.title': 'Our Mission',
    'about.subtitle': 'We\'re dedicated to providing premium herbal vaping products that support mental wellness through natural, evidence-based botanical blends.',
    'about.quality.title': 'Our Quality Standards',
    'about.quality.approach': 'Evidence-Based Formulation',
    'about.quality.compliance': 'Our Compliance Commitment',
    'about.trust.lab': 'Lab Tested',
    'about.trust.verified': '21+ Verified',
    'about.trust.coa': 'COA Available',
    'about.trust.shipping': 'Free Shipping $50+',
    'about.disclaimer': 'Not for use by minors. Avoid during pregnancy or nursing. Consult a healthcare provider before use if you have medical conditions or take medications.',
    
    // Education Page
    'education.title': 'Education Hub',
    'education.subtitle': 'Learn about the science behind herbal vaping and wellness',
    'education.intro.title': 'The Science of Herbal Vaping',
    'education.intro.desc': 'Understanding how vaporization preserves beneficial compounds while avoiding combustion.',
    'education.safety.title': 'Safety & Usage Guidelines',
    'education.safety.temperature.title': 'Temperature Control',
    'education.safety.temperature.desc': 'Optimal temperatures for different herbs and desired effects.',
    'education.safety.temperature.range': 'Recommended range: 160-204°C (320-400°F)',
    'education.safety.session.title': 'Session Management',
    'education.safety.session.desc': 'Proper timing and dosage for optimal benefits.',
    'education.safety.session.length': 'Recommended session: 5-15 minutes',
    'education.benefits.title': 'Health Benefits',
    'education.benefits.anxiety.title': 'Anxiety Relief',
    'education.benefits.anxiety.desc': 'How certain herbs can help reduce anxiety and promote calm.',
    'education.benefits.sleep.title': 'Sleep Support',
    'education.benefits.sleep.desc': 'Natural alternatives for better sleep quality.',
    'education.benefits.focus.title': 'Mental Clarity',
    'education.benefits.focus.desc': 'Herbs that may enhance focus and cognitive function.',
    'education.research.title': 'Research & Studies',
    'education.research.intro': 'Explore the scientific evidence behind herbal wellness.',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions? We\'re here to help. Reach out to our support team.',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.selectSubject': 'Select a subject...',
    'contact.form.productInquiry': 'Product Inquiry',
    'contact.form.orderStatus': 'Order Status',
    'contact.form.shipping': 'Shipping Question',
    'contact.form.returns': 'Returns & Refunds',
    'contact.form.safety': 'Safety & Usage',
    'contact.form.wholesale': 'Wholesale Inquiry',
    'contact.form.other': 'Other',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.form.success.desc': 'Thank you for contacting us. We\'ll get back to you within 1-2 business days at',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Business Hours',
    'contact.info.location': 'Location',
    'contact.info.responseTime': 'Response within 1-2 business days',
    'contact.info.weekdays': 'Monday - Friday',
    'contact.info.time': '9:00 AM - 6:00 PM CET',
    'contact.info.spain': 'Spain',
    'contact.info.shipping': 'We ship throughout Spain and Europe (where permitted)',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.track': 'How do I track my order?',
    'contact.faq.track.desc': 'You\'ll receive a tracking number via email once your order ships. Use this number to track your package on the carrier\'s website. Most orders arrive within 3-5 business days.',
    'contact.faq.returns': 'What is your return policy?',
    'contact.faq.returns.desc': 'We offer a 30-day satisfaction guarantee on unopened products. If you\'re not satisfied, contact us for a full refund. Opened products cannot be returned due to safety regulations.',
    'contact.faq.choose': 'How do I choose the right product?',
    'contact.faq.choose.desc': 'Browse by category (Anxiety Relief, Sleep Support, Focus & Clarity, etc.) or consult our Education Hub for detailed herb benefits. Start with core blends if you\'re new to herbal vaping.',
    'contact.faq.ship': 'Do you ship to my state?',
    'contact.faq.ship.desc': 'We ship to most US states. Some shipping restrictions may apply based on local regulations. Your shipping eligibility will be confirmed at checkout.',
    'contact.faq.lab': 'Are your products lab tested?',
    'contact.faq.lab.desc': 'Yes! Every batch undergoes third-party laboratory testing for purity, potency, and contaminants. Certificate of Analysis (COA) available via QR code on product packaging or upon request.',
    'contact.help.title': 'Need Help with Shipping or Returns?',
    'contact.help.desc': 'Our customer service team is here to assist you with any questions about shipping or returns.',
    'contact.disclaimer': 'For adults 21+ only. Not intended to diagnose, treat, cure, or prevent any disease.',
    
    // Footer
    'footer.about.title': 'MindVap',
    'footer.about.desc': 'Premium vaping herbs focused on natural mental wellness solutions. Quality-first, evidence-based formulations.',
    'footer.shop.title': 'Shop',
    'footer.shop.all': 'All Products',
    'footer.shop.anxiety': 'Anxiety Relief',
    'footer.shop.sleep': 'Sleep Support',
    'footer.shop.focus': 'Focus & Clarity',
    'footer.info.title': 'Information',
    'footer.info.about': 'About Us',
    'footer.info.education': 'Education Hub',
    'footer.info.contact': 'Contact',
    'footer.legal.title': 'Legal',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.shipping': 'Shipping & Returns',
    'footer.disclaimer': 'This product has not been evaluated by the FDA and is not intended to diagnose, treat, cure, or prevent any disease. Not for use by minors. Avoid during pregnancy or nursing.',
    'footer.copyright': '© 2025 MindVap. All rights reserved. Must be 21+ to purchase.',
    'footer.trust.lab': 'Lab Tested',
    'footer.trust.shipping': 'Free Shipping $50+',
    'footer.trust.verified': 'Age 21+ Verified',
    'footer.trust.coa': 'COA Available',
    
    // Age Gate
    'age.title': 'Age Verification Required',
    'age.subtitle': 'You must be 21 years or older to enter this site.',
    'age.verify': 'I am 21 years or older',
    'age.enter': 'Enter Site',
    'age.exit': 'Exit Site',
    'age.error': 'You must verify that you are 21 years of age or older to continue.',
    
    // Error Messages
    'error.required': 'This field is required',
    'error.email': 'Please enter a valid email address',
    'error.minLength': 'Must be at least {min} characters',
    'error.maxLength': 'Must be no more than {max} characters',
    'error.ageVerification': 'You must verify that you are 21 years of age or older to complete this purchase.',
    'error.fillFields': 'Please fill in all required fields.',
    'error.network': 'Network error. Please try again.',
    'error.payment': 'Payment failed. Please try again.',
    'error.unknown': 'An unexpected error occurred.',
    
    // Chat
    'chat.welcome': 'Hi! How can we help you today?',
    'chat.quickReplies.trackOrder': 'Track my order',
    'chat.quickReplies.productQuestions': 'Product questions',
    'chat.quickReplies.shippingInfo': 'Shipping info',
    'chat.quickReplies.other': 'Other',
    'chat.quickReplies.contactSupport': 'Contact support',
    'chat.header': 'Customer Support',
    'chat.inputPlaceholder': 'Type your message...',
    'chat.speakToHuman': 'Speak to a human',
    'chat.openAriaLabel': 'Open chat support',
    'chat.minimizeAriaLabel': 'Minimize chat',
    'chat.closeAriaLabel': 'Close chat',
    'chat.comingSoon': 'Chat functionality coming soon!',
    // Chat Bot Responses
    'chat.response.orderTracking': 'Please provide your order number and we\'ll help you track it. You can also check your order status in your account dashboard.',
    'chat.response.shipping': 'We offer standard shipping (5-7 days) and express shipping (2-3 days). Free shipping on orders over $50 (€75 in Europe).',
    'chat.response.returns': 'Our return policy allows returns within 30 days of purchase. Items must be in original condition. Contact support@mindvap.com for return instructions.',
    'chat.response.payment': 'We accept all major credit cards securely through Stripe. Your payment information is encrypted and protected.',
    'chat.response.product': 'Our herbal blends are carefully crafted using premium ingredients. Each product page contains detailed information about ingredients, benefits, and usage.',
    'chat.response.ageVerification': 'Yes, you must be 21 years or older to purchase our herbal products. This is required by law and we take age verification seriously.',
    'chat.response.international': 'Yes, we ship internationally! We currently ship to 30+ European countries with European shipping rates and VAT calculations.',
    'chat.response.contact': 'You can reach our support team at support@mindvap.com or through this chat. We typically respond within 2-4 hours during business hours.',
    'chat.response.pricing': 'Our prices vary by product and quantity. You can find all pricing information on our product pages. We offer competitive rates and free shipping on orders over $50.',
    'chat.response.fallback': 'Thanks for your message! A support agent will respond shortly. You can also email us at support@mindvap.com.',
    
    // Authentication - merged from auth.ts
    ...authTranslations.en
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.shop': 'Tienda',
    'nav.about': 'Acerca de',
    'nav.education': 'Educación',
    'nav.contact': 'Contacto',
    'nav.cart': 'Carrito',
    'nav.language': 'Idioma',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.remove': 'Quitar',
    'common.continue': 'Continuar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.submit': 'Enviar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.price': 'Precio',
    'common.quantity': 'Cantidad',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Impuesto',
    'common.shipping': 'Envío',
    'common.free': 'GRATIS',
    'common.explore': 'Explorar',
    'common.optional': 'Opcional',
    
    // Search
    'search.placeholder': 'Buscar productos y páginas...',
    'search.ariaLabel': 'Buscar en sitio web MindVap',
    'search.clear': 'Limpiar búsqueda',
    'search.searching': 'Buscando...',
    'search.noResults': 'No se encontraron resultados',
    'search.tryDifferent': 'Intenta con palabras diferentes',
    'search.products': 'Productos',
    'search.pages': 'Páginas',
    'search.viewAll': 'Ver todos los resultados',
    'search.resultsFor': 'Resultados para',
    'search.result': 'resultado',
    'search.results': 'resultados',
    'search.found': 'encontrado',
    
    // Registration
    'register.title': 'Crear Tu Cuenta',
    'register.subtitle': 'Únete a MindVap para soluciones de bienestar personalizadas',
    'register.pageTitle': 'Crear Tu Cuenta',
    'register.pageSubtitle': 'Únete a MindVap para acceso exclusivo a productos premium de bienestar herbal',
    'register.email': 'Dirección de Email',
    'register.emailPlaceholder': 'Ingresa tu dirección de email',
    'register.firstName': 'Nombre',
    'register.firstNamePlaceholder': 'Ingresa tu nombre',
    'register.lastName': 'Apellido',
    'register.lastNamePlaceholder': 'Ingresa tu apellido',
    'register.dateOfBirth': 'Fecha de Nacimiento',
    'register.age': 'Edad',
    'register.phone': 'Número de Teléfono',
    'register.phonePlaceholder': 'Ingresa tu número de teléfono',
    'register.password': 'Contraseña',
    'register.passwordPlaceholder': 'Crea una contraseña segura',
    'register.confirmPassword': 'Confirmar Contraseña',
    'register.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'register.passwordStrength': 'Fortaleza de Contraseña',
    'register.passwordMismatch': 'Las contraseñas no coinciden',
    'register.invalidPhone': 'Por favor ingresa un número de teléfono válido',
    'register.ageRequirement': 'Debes tener al menos 21 años',
    'register.termsRequired': 'Debes aceptar los Términos de Servicio',
    'register.privacyRequired': 'Debes aceptar la Política de Privacidad',
    'register.dataProcessingRequired': 'Debes aceptar el consentimiento de procesamiento de datos',
    'register.agreeTo': 'Acepto los',
    'register.termsOfService': 'Términos de Servicio',
    'register.privacyPolicy': 'Política de Privacidad',
    'register.dataProcessingConsent': 'Consiento el procesamiento de mis datos personales para la creación de cuenta y propósitos de comunicación',
    'register.marketingConsent': 'Me gustaría recibir emails de marketing sobre nuevos productos y consejos de bienestar',
    'register.createAccount': 'Crear Cuenta',
    'register.creating': 'Creando Cuenta...',
    'register.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'register.signIn': 'Iniciar Sesión',
    'register.registrationSuccess': '¡Registro exitoso!',
    'register.checkEmailVerification': 'Por favor revisa tu email para verificar tu cuenta',
    'register.redirecting': 'Redirigiendo al inicio de sesión...',
    'register.accountCreated': '¡Cuenta Creada Exitosamente!',
    'register.registrationFailed': 'El registro falló. Por favor intenta de nuevo.',
    'register.whyJoin': '¿Por Qué Unirse a MindVap?',
    'register.benefit1.title': 'Productos Exclusivos',
    'register.benefit1.desc': 'Acceso a mezclas herbales premium probadas en laboratorio',
    'register.benefit2.title': 'Guía de Bienestar',
    'register.benefit2.desc': 'Recomendaciones personalizadas basadas en tus objetivos',
    'register.benefit3.title': 'Contenido Educativo',
    'register.benefit3.desc': 'Conocimiento experto sobre bienestar herbal y uso',
    'register.benefit4.title': 'Beneficios de Miembro',
    'register.benefit4.desc': 'Precios especiales y acceso anticipado a nuevos productos',
    'register.securityNotice': 'Tu Seguridad es Nuestra Prioridad',
    'register.securityDesc': 'Usamos encriptación estándar de la industria y nunca compartimos tu información personal.',
    'register.ageVerification': 'Verificación de Edad Requerida',
    'register.ageNotice': 'Al registrarte, certificas que tienes 21 años o más.',
    'register.termsAcceptance': 'Al crear una cuenta, aceptas nuestros',
    
    // Home Page
    'home.hero.title': 'Bienestar Natural a través de Vaporización Herbal Premium',
    'home.hero.subtitle': 'Descubre mezclas de hierbas basadas en evidencia creadas para el bienestar mental. Formulaciones probadas en laboratorio, sin aditivos, diseñadas para adultos que buscan alivio natural de la ansiedad, mejor sueño y mayor enfoque.',
    'home.hero.cta': 'Explorar Nuestra Colección',
    'home.trust.lab': 'Probado en Laboratorio',
    'home.trust.shipping': 'Envío Gratis $50+',
    'home.trust.verified': '21+ Verificado',
    'home.trust.coa': 'COA Disponible',
    'home.categories.title': 'Comprar por Objetivo de Bienestar',
    'home.categories.subtitle': 'Explora nuestras cinco categorías cuidadosamente elaboradas, cada una diseñada para apoyar necesidades específicas de bienestar mental',
    'home.categories.anxiety': 'Alivio de Ansiedad',
    'home.categories.sleep': 'Apoyo para el Sueño',
    'home.categories.focus': 'Enfoque y Claridad',
    'home.categories.stress': 'Alivio del Estrés',
    'home.categories.mood': 'Apoyo del Estado de Ánimo',
    'home.categories.keyHerbs': 'Hierbas clave:',
    'home.featured.title': 'Colección de Bienestar Premium',
    'home.featured.subtitle': 'Nuestras mezclas más populares, elegidas por su calidad excepcional y satisfacción del cliente',
    'home.featured.cta': 'Ver Todos los Productos',
    'home.benefits.title': 'Bienestar Basado en Evidencia',
    'home.benefits.ashwagandha.title': 'Ashwagandha para el Estrés',
    'home.benefits.ashwagandha.desc': 'Meta-análisis de ECAs muestra grandes reducciones en el estrés (SMD -1.75) y ansiedad (SMD -1.55) con efectos favorables en dosis de 300-600mg/día.',
    'home.benefits.chamomile.title': 'Manzanilla para la Ansiedad',
    'home.benefits.chamomile.desc': 'Revisión sistemática de 10 ensayos clínicos concluyó que la manzanilla mejoró la ansiedad en TAG, insomnio y condiciones relacionadas con el estrés.',
    'home.benefits.lavender.title': 'Lavanda para la Relajación',
    'home.benefits.lavender.desc': 'Efectos significativos de reducción de ansiedad en 11 ensayos a través de aromaterapia por inhalación, modulando la actividad del sistema límbico.',
    'home.benefits.researched': 'Hierbas Investigadas',
    'home.benefits.researched.desc': 'Cada mezcla se formula basándose en investigación clínica y conocimiento herbal tradicional',
    'home.howto.title': 'Cómo Usar',
    'home.howto.subtitle': 'Pasos simples para una experiencia óptima de vaporización herbal',
    'home.howto.step1.title': 'Elige Tu Mezcla',
    'home.howto.step1.desc': 'Selecciona una mezcla basándote en tu objetivo de bienestar - alivio de ansiedad, apoyo para el sueño, o claridad mental',
    'home.howto.step2.title': 'Establece la Temperatura',
    'home.howto.step2.desc': 'Comienza a 160-177°C (320-350°F) para sabor, sube a 177-204°C (350-400°F) para extracción equilibrada',
    'home.howto.step3.title': 'Disfruta Conscientemente',
    'home.howto.step3.desc': 'Duración de sesión: 5-15 minutos. Evita temperaturas superiores a 221°C (430°F) para prevenir combustión',
    'home.cta.title': 'Comienza Tu Viaje de Bienestar',
    'home.cta.subtitle': 'Explora nuestra colección completa de mezclas de hierbas premium diseñadas para el bienestar mental natural',
    'home.cta.cta': 'Explorar Nuestra Colección',
    
    // Shop Page
    'shop.title': 'Nuestros Productos',
    'shop.subtitle': 'Descubre nuestra colección completa de mezclas de hierbas premium para vaporizar',
    'shop.filter.all': 'Todos los Productos',
    'shop.filter.anxiety': 'Alivio de Ansiedad',
    'shop.filter.sleep': 'Apoyo para el Sueño',
    'shop.filter.focus': 'Enfoque y Claridad',
    'shop.filter.mood': 'Apoyo del Estado de Ánimo',
    'shop.filter.stress': 'Alivio del Estrés',
    'shop.filter.category': 'Categoría',
    'shop.filter.priceRange': 'Rango de Precio',
    'shop.filter.clearAll': 'Limpiar Todos los Filtros',
    'shop.filter.filters': 'Filtros',
    'shop.filter.applyFilters': 'Aplicar Filtros',
    'shop.filter.noProducts': 'No se encontraron productos',
    'shop.filter.clearFilters': 'Limpiar filtros',
    'shop.filter.tryAdjusting': 'Intenta ajustar tus filtros',
    'shop.productsAvailable': 'productos disponibles',
    'shop.onlyLeft': '¡Solo quedan {count}!',
    'shop.addToCart': 'Agregar al Carrito',
    'shop.viewDetails': 'Ver Detalles',
    'shop.outOfStock': 'Agotado',
    'shop.inStock': 'En Stock',
    'shop.rating': 'Calificación',
    'shop.reviews': 'reseñas',
    
    // Product Detail
    'product.details': 'Detalles del Producto',
    'product.description': 'Descripción',
    'product.benefits': 'Beneficios',
    'product.usage': 'Instrucciones de Uso',
    'product.safety': 'Información de Seguridad',
    'product.herbs': 'Mezcla de Hierbas',
    'product.temperature': 'Temperatura Óptima',
    'product.category': 'Categoría',
    'product.stock': 'Nivel de Stock',
    'product.addToCart': 'Agregar al Carrito',
    'product.addedToCart': '¡Agregado al Carrito!',
    'product.goToCart': 'Ir al Carrito',
    'product.continueShopping': 'Continuar Comprando',
    'product.notFound': 'Producto no encontrado',
    'product.returnToShop': 'Volver a la Tienda',
    'product.tab.overview': 'Resumen',
    'product.tab.benefits': 'Beneficios',
    'product.tab.usage': 'Guías de Uso',
    'product.tab.safety': 'Seguridad y Contraindicaciones',
    'product.productDescription': 'Descripción del Producto',
    'product.keyHerbs': 'Hierbas Clave',
    'product.temperatureRange': 'Rango de Temperatura',
    'product.evidenceBasedBenefits': 'Beneficios Basados en Evidencia',
    'product.usageGuidelines': 'Guías de Uso',
    'product.safetyContraindications': 'Seguridad y Contraindicaciones',
    'product.quantity': 'Cantidad',
    'product.wishlist': 'Lista de Deseos',
    'product.share': 'Compartir',
    'product.labTested': 'Probado en Laboratorio con COA',
    'product.freeShipping': 'Envío Gratis en Pedidos $50+',
    'product.easyReturns': 'Devoluciones Fáciles de 30 Días',
    'product.ageVerified': '21+ Verificado',
    'product.onlyLeft': '¡Solo quedan {count} en stock!',
    'product.inStock': 'En Stock',
    
    // Cart Page
    'cart.title': 'Carrito de Compras',
    'cart.empty': 'Tu Carrito Está Vacío',
    'cart.empty.desc': 'Descubre nuestras mezclas de hierbas premium y agrégalas a tu carrito.',
    'cart.browseProducts': 'Explorar Productos',
    'cart.orderSummary': 'Resumen del Pedido',
    'cart.proceedToCheckout': 'Proceder al Pago',
    'cart.continueShopping': 'Continuar Comprando',
    'cart.freeShippingThreshold': 'Agregar',
    'cart.freeShippingMessage': 'más para envío gratis!',
    'cart.removeItem': 'Quitar artículo',
    'cart.updateQuantity': 'Actualizar cantidad',
    
    // Checkout Page
    'checkout.title': 'Pago Seguro',
    'checkout.contactInfo': 'Información de Contacto',
    'checkout.email': 'Dirección de Email',
    'checkout.shippingAddress': 'Dirección de Envío',
    'checkout.firstName': 'Nombre',
    'checkout.lastName': 'Apellido',
    'checkout.address': 'Dirección',
    'checkout.city': 'Ciudad',
    'checkout.state': 'Provincia',
    'checkout.zipCode': 'Código Postal',
    'checkout.country': 'País',
    'checkout.paymentInfo': 'Información de Pago',
    'checkout.payment.desc': 'Completa la información anterior, luego haz clic en el botón de abajo para proceder al pago.',
    'checkout.ageVerification': 'Verificación de Edad',
    'checkout.ageVerification.text': 'Certifico que tengo 21 años de edad o más. Entiendo que estos productos no están destinados a diagnosticar, tratar, curar o prevenir ninguna enfermedad y no han sido evaluados por la FDA.',
    'checkout.continueToPayment': 'Continuar al Pago',
    'checkout.preparingPayment': 'Preparando Pago...',
    'checkout.completePurchase': 'Completar Compra Segura',
    'checkout.processingPayment': 'Procesando Pago...',
    'checkout.securePayment': 'Pago SSL encriptado seguro',
    'checkout.orderComplete': '¡Pedido Completo!',
    'checkout.orderComplete.desc': 'Gracias por tu compra. Recibirás un email de confirmación en breve con información de seguimiento.',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.redirecting': 'Redirigiendo a la página principal...',
    
    // About Page
    'about.title': 'Nuestra Misión',
    'about.subtitle': 'Estamos dedicados a proporcionar productos premium de hierbas para vaporizar que apoyan el bienestar mental a través de mezclas botánicas naturales basadas en evidencia.',
    'about.quality.title': 'Nuestros Estándares de Calidad',
    'about.quality.approach': 'Formulación Basada en Evidencia',
    'about.quality.compliance': 'Nuestro Compromiso de Cumplimiento',
    'about.trust.lab': 'Probado en Laboratorio',
    'about.trust.verified': '21+ Verificado',
    'about.trust.coa': 'COA Disponible',
    'about.trust.shipping': 'Envío Gratis $50+',
    'about.disclaimer': 'No para uso por menores. Evitar durante el embarazo o lactancia. Consultar a un proveedor de atención médica antes del uso si tiene condiciones médicas o toma medicamentos.',
    
    // Education Page
    'education.title': 'Centro de Educación',
    'education.subtitle': 'Aprende sobre la ciencia detrás de la vaporización herbal y el bienestar',
    'education.intro.title': 'La Ciencia de la Vaporización Herbal',
    'education.intro.desc': 'Entendiendo cómo la vaporización preserva compuestos beneficiosos mientras evita la combustión.',
    'education.safety.title': 'Guías de Seguridad y Uso',
    'education.safety.temperature.title': 'Control de Temperatura',
    'education.safety.temperature.desc': 'Temperaturas óptimas para diferentes hierbas y efectos deseados.',
    'education.safety.temperature.range': 'Rango recomendado: 160-204°C (320-400°F)',
    'education.safety.session.title': 'Gestión de Sesiones',
    'education.safety.session.desc': 'Tiempo y dosis adecuados para beneficios óptimos.',
    'education.safety.session.length': 'Sesión recomendada: 5-15 minutos',
    'education.benefits.title': 'Beneficios para la Salud',
    'education.benefits.anxiety.title': 'Alivio de Ansiedad',
    'education.benefits.anxiety.desc': 'Cómo ciertas hierbas pueden ayudar a reducir la ansiedad y promover la calma.',
    'education.benefits.sleep.title': 'Apoyo para el Sueño',
    'education.benefits.sleep.desc': 'Alternativas naturales para mejor calidad de sueño.',
    'education.benefits.focus.title': 'Claridad Mental',
    'education.benefits.focus.desc': 'Hierbas que pueden mejorar el enfoque y la función cognitiva.',
    'education.research.title': 'Investigación y Estudios',
    'education.research.intro': 'Explora la evidencia científica detrás del bienestar herbal.',
    
    // Contact Page
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Tienes preguntas? Estamos aquí para ayudar. Ponte en contacto con nuestro equipo de soporte.',
    'contact.form.title': 'Envíanos un mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.selectSubject': 'Selecciona un asunto...',
    'contact.form.productInquiry': 'Consulta de Producto',
    'contact.form.orderStatus': 'Estado del Pedido',
    'contact.form.shipping': 'Pregunta de Envío',
    'contact.form.returns': 'Devoluciones y Reembolsos',
    'contact.form.safety': 'Seguridad y Uso',
    'contact.form.wholesale': 'Consulta de Mayorista',
    'contact.form.other': 'Otro',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado exitosamente!',
    'contact.form.success.desc': 'Gracias por contactarnos. Te responderemos dentro de 1-2 días hábiles en',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Horarios de Atención',
    'contact.info.location': 'Ubicación',
    'contact.info.responseTime': 'Respuesta dentro de 1-2 días hábiles',
    'contact.info.weekdays': 'Lunes - Viernes',
    'contact.info.time': '9:00 AM - 6:00 PM CET',
    'contact.info.spain': 'España',
    'contact.info.shipping': 'Enviamos por toda España y Europa (donde esté permitido)',
    'contact.faq.title': 'Preguntas Frecuentes',
    'contact.faq.track': '¿Cómo rastree mi pedido?',
    'contact.faq.track.desc': 'Recibirás un número de seguimiento por email una vez que se envíe tu pedido. Usa este número para rastrear tu paquete en el sitio web del transportista. La mayoría de los pedidos llegan dentro de 3-5 días hábiles.',
    'contact.faq.returns': '¿Cuál es su política de devoluciones?',
    'contact.faq.returns.desc': 'Ofrecemos una garantía de satisfacción de 30 días en productos sin abrir. Si no estás satisfecho, contáctanos para un reembolso completo. Los productos abiertos no pueden devolverse debido a regulaciones de seguridad.',
    'contact.faq.choose': '¿Cómo elijo el producto correcto?',
    'contact.faq.choose.desc': 'Navega por categoría (Alivio de Ansiedad, Apoyo para el Sueño, Enfoque y Claridad, etc.) o consulta nuestro Centro de Educación para beneficios detallados de hierbas. Comienza con mezclas básicas si eres nuevo en la vaporización de hierbas.',
    'contact.faq.ship': '¿Envían a mi estado?',
    'contact.faq.ship.desc': 'Enviamos a la mayoría de los estados de EE.UU. Algunas restricciones de envío pueden aplicarse según las regulaciones locales. Tu elegibilidad de envío se confirmará al finalizar la compra.',
    'contact.faq.lab': '¿Sus productos son probados en laboratorio?',
    'contact.faq.lab.desc': '¡Sí! Cada lote se somete a pruebas de laboratorio de terceros para pureza, potencia y contaminantes. Certificado de Análisis (COA) disponible a través de código QR en el empaque del producto o bajo petición.',
    'contact.help.title': '¿Necesitas Ayuda con Envíos o Devoluciones?',
    'contact.help.desc': 'Nuestro equipo de servicio al cliente está aquí para ayudarte con cualquier pregunta sobre envíos o devoluciones.',
    'contact.disclaimer': 'Solo para adultos de 21 años en adelante. No destinado a diagnosticar, tratar, curar o prevenir ninguna enfermedad.',
    
    // Footer
    'footer.about.title': 'MindVap',
    'footer.about.desc': 'Hierbas premium para vaporizar enfocadas en soluciones naturales de bienestar mental. Calidad primero, formulaciones basadas en evidencia.',
    'footer.shop.title': 'Tienda',
    'footer.shop.all': 'Todos los Productos',
    'footer.shop.anxiety': 'Alivio de Ansiedad',
    'footer.shop.sleep': 'Apoyo para el Sueño',
    'footer.shop.focus': 'Enfoque y Claridad',
    'footer.info.title': 'Información',
    'footer.info.about': 'Acerca de Nosotros',
    'footer.info.education': 'Centro de Educación',
    'footer.info.contact': 'Contacto',
    'footer.legal.title': 'Legal',
    'footer.legal.privacy': 'Política de Privacidad',
    'footer.legal.terms': 'Términos de Servicio',
    'footer.legal.shipping': 'Envíos y Devoluciones',
    'footer.disclaimer': 'Este producto no ha sido evaluado por la FDA y no está destinado a diagnosticar, tratar, curar o prevenir ninguna enfermedad. No para uso por menores. Evitar durante el embarazo o lactancia.',
    'footer.copyright': '© 2025 MindVap. Todos los derechos reservados. Debe ser 21+ para comprar.',
    'footer.trust.lab': 'Probado en Laboratorio',
    'footer.trust.shipping': 'Envío Gratis $50+',
    'footer.trust.verified': '21+ Verificado',
    'footer.trust.coa': 'COA Disponible',
    
    // Age Gate
    'age.title': 'Verificación de Edad Requerida',
    'age.subtitle': 'Debes tener 21 años o más para entrar a este sitio.',
    'age.verify': 'Tengo 21 años o más',
    'age.enter': 'Entrar al Sitio',
    'age.exit': 'Salir del Sitio',
    'age.error': 'Debes verificar que tienes 21 años de edad o más para continuar.',
    
    // Error Messages
    'error.required': 'Este campo es requerido',
    'error.email': 'Por favor ingresa una dirección de email válida',
    'error.minLength': 'Debe tener al menos {min} caracteres',
    'error.maxLength': 'No debe tener más de {max} caracteres',
    'error.ageVerification': 'Debes verificar que tienes 21 años de edad o más para completar esta compra.',
    'error.fillFields': 'Por favor completa todos los campos requeridos.',
    'error.network': 'Error de red. Por favor intenta de nuevo.',
    'error.payment': 'Pago fallido. Por favor intenta de nuevo.',
    'error.unknown': 'Ocurrió un error inesperado.',
    
    // Chat
    'chat.welcome': '¡Hola! ¿Cómo podemos ayudarte hoy?',
    'chat.quickReplies.trackOrder': 'Rastrear mi pedido',
    'chat.quickReplies.productQuestions': 'Preguntas sobre productos',
    'chat.quickReplies.shippingInfo': 'Información de envío',
    'chat.quickReplies.other': 'Otro',
    'chat.quickReplies.contactSupport': 'Contactar soporte',
    'chat.header': 'Soporte al Cliente',
    'chat.inputPlaceholder': 'Escribe tu mensaje...',
    'chat.speakToHuman': 'Hablar con una persona',
    'chat.openAriaLabel': 'Abrir soporte de chat',
    'chat.minimizeAriaLabel': 'Minimizar chat',
    'chat.closeAriaLabel': 'Cerrar chat',
    'chat.comingSoon': '¡Funcionalidad de chat próximamente!',
    // Chat Bot Responses
    'chat.response.orderTracking': 'Por favor proporciona tu número de pedido y te ayudaremos a rastrearlo. También puedes verificar el estado de tu pedido en el panel de tu cuenta.',
    'chat.response.shipping': 'Ofrecemos envío estándar (5-7 días) y envío express (2-3 días). Envío gratis en pedidos superiores a $50 (€75 en Europa).',
    'chat.response.returns': 'Nuestra política de devoluciones permite devoluciones dentro de 30 días de compra. Los artículos deben estar en condición original. Contacta support@mindvap.com para instrucciones de devolución.',
    'chat.response.payment': 'Aceptamos todas las tarjetas de crédito de forma segura a través de Stripe. Tu información de pago está encriptada y protegida.',
    'chat.response.product': 'Nuestras mezclas de hierbas están cuidadosamente elaboradas usando ingredientes premium. Cada página de producto contiene información detallada sobre ingredientes, beneficios y uso.',
    'chat.response.ageVerification': 'Sí, debes tener 21 años o más para comprar nuestros productos de hierbas. Esto es requerido por ley y tomamos la verificación de edad en serio.',
    'chat.response.international': '¡Sí, enviamos internacionalmente! Actualmente enviamos a más de 30 países europeos con tarifas de envío europeas y cálculos de IVA.',
    'chat.response.contact': 'Puedes contactar a nuestro equipo de soporte en support@mindvap.com o a través de este chat. Típicamente respondemos dentro de 2-4 horas durante horarios de negocio.',
    'chat.response.pricing': 'Nuestros precios varían según el producto y cantidad. Puedes encontrar toda la información de precios en nuestras páginas de productos. Ofrecemos tarifas competitivas y envío gratis en pedidos superiores a $50.',
    'chat.response.fallback': '¡Gracias por tu mensaje! Un agente de soporte responderá pronto. También puedes enviarnos un email a support@mindvap.com.',
    
    // Authentication - merged from auth.ts
    ...authTranslations.es
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Negozio',
    'nav.about': 'Chi Siamo',
    'nav.education': 'Educazione',
    'nav.contact': 'Contatti',
    'nav.cart': 'Carrello',
    'nav.language': 'Lingua',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.add': 'Aggiungi',
    'common.remove': 'Rimuovi',
    'common.continue': 'Continua',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.submit': 'Invia',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.price': 'Prezzo',
    'common.quantity': 'Quantità',
    'common.total': 'Totale',
    'common.subtotal': 'Subtotale',
    'common.tax': 'Tasse',
    'common.shipping': 'Spedizione',
    'common.free': 'GRATIS',
    'common.explore': 'Esplora',
    'common.optional': 'Opzionale',
    
    // Search
    'search.placeholder': 'Cerca prodotti e pagine...',
    'search.ariaLabel': 'Cerca nel sito web MindVap',
    'search.clear': 'Cancella ricerca',
    'search.searching': 'Ricerca in corso...',
    'search.noResults': 'Nessun risultato trovato',
    'search.tryDifferent': 'Prova con parole diverse',
    'search.products': 'Prodotti',
    'search.pages': 'Pagine',
    'search.viewAll': 'Vedi tutti i risultati',
    'search.resultsFor': 'Risultati per',
    'search.result': 'risultato',
    'search.results': 'risultati',
    'search.found': 'trovato',
    
    // Registration
    'register.title': 'Crea il Tuo Account',
    'register.subtitle': 'Unisciti a MindVap per soluzioni di benessere personalizzate',
    'register.pageTitle': 'Crea il Tuo Account',
    'register.pageSubtitle': 'Unisciti a MindVap per accesso esclusivo a prodotti premium di benessere erboristico',
    'register.email': 'Indirizzo Email',
    'register.emailPlaceholder': 'Inserisci il tuo indirizzo email',
    'register.firstName': 'Nome',
    'register.firstNamePlaceholder': 'Inserisci il tuo nome',
    'register.lastName': 'Cognome',
    'register.lastNamePlaceholder': 'Inserisci il tuo cognome',
    'register.dateOfBirth': 'Data di Nascita',
    'register.age': 'Età',
    'register.phone': 'Numero di Telefono',
    'register.phonePlaceholder': 'Inserisci il tuo numero di telefono',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Crea una password sicura',
    'register.confirmPassword': 'Conferma Password',
    'register.confirmPasswordPlaceholder': 'Conferma la tua password',
    'register.passwordStrength': 'Sicurezza Password',
    'register.passwordMismatch': 'Le password non corrispondono',
    'register.invalidPhone': 'Per favore inserisci un numero di telefono valido',
    'register.ageRequirement': 'Devi avere almeno 21 anni',
    'register.termsRequired': 'Devi accettare i Termini di Servizio',
    'register.privacyRequired': 'Devi accettare l\'Informativa sulla Privacy',
    'register.dataProcessingRequired': 'Devi accettare il consenso al trattamento dei dati',
    'register.agreeTo': 'Accetto i',
    'register.termsOfService': 'Termini di Servizio',
    'register.privacyPolicy': 'Informativa sulla Privacy',
    'register.dataProcessingConsent': 'Consento al trattamento dei miei dati personali per la creazione dell\'account e scopi di comunicazione',
    'register.marketingConsent': 'Vorrei ricevere email di marketing su nuovi prodotti e consigli di benessere',
    'register.createAccount': 'Crea Account',
    'register.creating': 'Creazione Account...',
    'register.alreadyHaveAccount': 'Hai già un account?',
    'register.signIn': 'Accedi',
    'register.registrationSuccess': 'Registrazione riuscita!',
    'register.checkEmailVerification': 'Per favore controlla la tua email per verificare il tuo account',
    'register.redirecting': 'Reindirizzamento al login...',
    'register.accountCreated': 'Account Creato con Successo!',
    'register.registrationFailed': 'Registrazione fallita. Per favore riprova.',
    'register.whyJoin': 'Perché Unirti a MindVap?',
    'register.benefit1.title': 'Prodotti Esclusivi',
    'register.benefit1.desc': 'Accesso a miscele erboristiche premium testate in laboratorio',
    'register.benefit2.title': 'Guida al Benessere',
    'register.benefit2.desc': 'Raccomandazioni personalizzate basate sui tuoi obiettivi',
    'register.benefit3.title': 'Contenuto Educativo',
    'register.benefit3.desc': 'Conoscenza esperta su benessere erboristico e uso',
    'register.benefit4.title': 'Vantaggi del Membro',
    'register.benefit4.desc': 'Prezzi speciali e accesso anticipato a nuovi prodotti',
    'register.securityNotice': 'La Tua Sicurezza è la Nostra Priorità',
    'register.securityDesc': 'Usiamo crittografia standard del settore e non condividiamo mai le tue informazioni personali.',
    'register.ageVerification': 'Verifica dell\'Età Richiesta',
    'register.ageNote': 'Registrandoti, certifichi di avere 21 anni o più.',
    'register.termsAcceptance': 'Creando un account, accetti i nostri',
    
    // Home Page
    'home.hero.title': 'Benessere Naturale attraverso la Vaporizzazione Erboristica Premium',
    'home.hero.subtitle': 'Scopri miscele di erbe basate su evidenze create per il benessere mentale. Formulazioni testate in laboratorio, senza additivi, progettate per adulti che cercano sollievo naturale dall ansia, miglior sonno e maggiore concentrazione.',
    'home.hero.cta': 'Esplora la Nostra Collezione',
    'home.trust.lab': 'Testato in Laboratorio',
    'home.trust.shipping': 'Spedizione Gratis $50+',
    'home.trust.verified': '21+ Verificato',
    'home.trust.coa': 'COA Disponibile',
    'home.categories.title': 'Acquista per Obiettivo di Benessere',
    'home.categories.subtitle': 'Esplora le nostre cinque categorie accuratamente realizzate, ciascuna progettata per supportare specifiche esigenze di benessere mentale',
    'home.categories.anxiety': 'Sollievo dall Ansia',
    'home.categories.sleep': 'Supporto per il Sonno',
    'home.categories.focus': 'Focus e Chiarezza',
    'home.categories.stress': 'Sollievo dello Stress',
    'home.categories.mood': 'Supporto dell Umore',
    'home.categories.keyHerbs': 'Erbe chiave:',
    'home.featured.title': 'Collezione Benessere Premium',
    'home.featured.subtitle': 'Le nostre miscele più popolari, scelte per la loro qualità eccezionale e soddisfazione del cliente',
    'home.featured.cta': 'Vedi Tutti i Prodotti',
    'home.benefits.title': 'Benessere Basato su Evidenze',
    'home.benefits.ashwagandha.title': 'Ashwagandha per lo Stress',
    'home.benefits.ashwagandha.desc': 'Meta-analisi di RCT mostra grandi riduzioni dello stress (SMD -1.75) e dell ansia (SMD -1.55) con effetti favorevoli a dosi di 300-600mg/giorno.',
    'home.benefits.chamomile.title': 'Camomilla per l Ansia',
    'home.benefits.chamomile.desc': 'Revisione sistematica di 10 studi clinici ha concluso che la camomilla ha migliorato l ansia in GAD, insonnia e condizioni legate allo stress.',
    'home.benefits.lavender.title': 'Lavanda per il Rilassamento',
    'home.benefits.lavender.desc': 'Significativi effetti di riduzione dell ansia in 11 studi attraverso l aromaterapia per inalazione, modulando l attività del sistema limbico.',
    'home.benefits.researched': 'Erbe Ricercate',
    'home.benefits.researched.desc': 'Ogni miscela è formulata basandosi sulla ricerca clinica e la conoscenza erboristica tradizionale',
    'home.howto.title': 'Come Usare',
    'home.howto.subtitle': 'Semplici passi per un esperienza ottimale di vaporizzazione erboristica',
    'home.howto.step1.title': 'Scegli la Tua Miscela',
    'home.howto.step1.desc': 'Seleziona una miscela basata sul tuo obiettivo di benessere - sollievo dall ansia, supporto per il sonno, o chiarezza mentale',
    'home.howto.step2.title': 'Imposta la Temperatura',
    'home.howto.step2.desc': 'Inizia a 160-177°C (320-350°F) per il sapore, aumenta a 177-204°C (350-400°F) per estrazione equilibrata',
    'home.howto.step3.title': 'Goditi Consapevolmente',
    'home.howto.step3.desc': 'Durata sessione: 5-15 minuti. Evita temperature superiori a 221°C (430°F) per prevenire combustione',
    'home.cta.title': 'Inizia il Tuo Viaggio di Benessere',
    'home.cta.subtitle': 'Esplora la nostra collezione completa di miscele di erbe premium progettate per il benessere mentale naturale',
    'home.cta.cta': 'Esplora la Nostra Collezione',
    
    // Shop Page
    'shop.title': 'I Nostri Prodotti',
    'shop.subtitle': 'Scopri la nostra collezione completa di miscele di erbe premium per vaporizzare',
    'shop.filter.all': 'Tutti i Prodotti',
    'shop.filter.anxiety': 'Sollievo dall Ansia',
    'shop.filter.sleep': 'Supporto per il Sonno',
    'shop.filter.focus': 'Focus e Chiarezza',
    'shop.filter.mood': 'Supporto dell Umore',
    'shop.filter.stress': 'Sollievo dello Stress',
    'shop.filter.category': 'Categoria',
    'shop.filter.priceRange': 'Fascia di Prezzo',
    'shop.filter.clearAll': 'Cancella Tutti i Filtri',
    'shop.filter.filters': 'Filtri',
    'shop.filter.applyFilters': 'Applica Filtri',
    'shop.filter.noProducts': 'Nessun prodotto trovato',
    'shop.filter.clearFilters': 'Cancella filtri',
    'shop.filter.tryAdjusting': 'Prova a regolare i tuoi filtri',
    'shop.productsAvailable': 'prodotti disponibili',
    'shop.onlyLeft': 'Solo {count} rimasti!',
    'shop.addToCart': 'Aggiungi al Carrello',
    'shop.viewDetails': 'Vedi Dettagli',
    'shop.outOfStock': 'Esaurito',
    'shop.inStock': 'In Stock',
    'shop.rating': 'Valutazione',
    'shop.reviews': 'recensioni',
    
    // Product Detail
    'product.details': 'Dettagli del Prodotto',
    'product.description': 'Descrizione',
    'product.benefits': 'Benefici',
    'product.usage': 'Istruzioni per l Uso',
    'product.safety': 'Informazioni sulla Sicurezza',
    'product.herbs': 'Miscela di Erbe',
    'product.temperature': 'Temperatura Ottimale',
    'product.category': 'Categoria',
    'product.stock': 'Livello di Scorte',
    'product.addToCart': 'Aggiungi al Carrello',
    'product.addedToCart': 'Aggiunto al Carrello!',
    'product.goToCart': 'Vai al Carrello',
    'product.continueShopping': 'Continua lo Shopping',
    'product.notFound': 'Prodotto non trovato',
    'product.returnToShop': 'Torna al Negozio',
    'product.tab.overview': 'Panoramica',
    'product.tab.benefits': 'Benefici',
    'product.tab.usage': 'Istruzioni per l Uso',
    'product.tab.safety': 'Sicurezza e Controindicazioni',
    'product.productDescription': 'Descrizione del Prodotto',
    'product.keyHerbs': 'Erbe Chiave',
    'product.temperatureRange': 'Range di Temperatura',
    'product.evidenceBasedBenefits': 'Benefici Basati su Evidenze',
    'product.usageGuidelines': 'Istruzioni per l Uso',
    'product.safetyContraindications': 'Sicurezza e Controindicazioni',
    'product.quantity': 'Quantità',
    'product.wishlist': 'Lista dei Desideri',
    'product.share': 'Condividi',
    'product.labTested': 'Testato in Laboratorio con COA',
    'product.freeShipping': 'Spedizione Gratis su Ordini $50+',
    'product.easyReturns': 'Resi Facili di 30 Giorni',
    'product.ageVerified': '21+ Verificato',
    'product.onlyLeft': 'Solo {count} rimasti in stock!',
    'product.inStock': 'In Stock',
    
    // Cart Page
    'cart.title': 'Carrello della Spesa',
    'cart.empty': 'Il Tuo Carrello è Vuoto',
    'cart.empty.desc': 'Scopri le nostre miscele di erbe premium e aggiungile al tuo carrello.',
    'cart.browseProducts': 'Esplora Prodotti',
    'cart.orderSummary': 'Riepilogo Ordine',
    'cart.proceedToCheckout': 'Procedi al Checkout',
    'cart.continueShopping': 'Continua lo Shopping',
    'cart.freeShippingThreshold': 'Aggiungi',
    'cart.freeShippingMessage': 'in più per la spedizione gratuita!',
    'cart.removeItem': 'Rimuovi articolo',
    'cart.updateQuantity': 'Aggiorna quantità',
    
    // Checkout Page
    'checkout.title': 'Checkout Sicuro',
    'checkout.contactInfo': 'Informazioni di Contatto',
    'checkout.email': 'Indirizzo Email',
    'checkout.shippingAddress': 'Indirizzo di Spedizione',
    'checkout.firstName': 'Nome',
    'checkout.lastName': 'Cognome',
    'checkout.address': 'Indirizzo',
    'checkout.city': 'Città',
    'checkout.state': 'Provincia',
    'checkout.zipCode': 'CAP',
    'checkout.country': 'Paese',
    'checkout.paymentInfo': 'Informazioni di Pagamento',
    'checkout.payment.desc': 'Completa le informazioni sopra, poi clicca il pulsante sotto per procedere al pagamento.',
    'checkout.ageVerification': 'Verifica dell Età',
    'checkout.ageVerification.text': 'Certifico di avere 21 anni di età o più. Capisco che questi prodotti non sono destinati a diagnosticare, trattare, curare o prevenire alcuna malattia e non sono stati valutati dalla FDA.',
    'checkout.continueToPayment': 'Continua al Pagamento',
    'checkout.preparingPayment': 'Preparazione Pagamento...',
    'checkout.completePurchase': 'Completa Acquisto Sicuro',
    'checkout.processingPayment': 'Elaborazione Pagamento...',
    'checkout.securePayment': 'Pagamento SSL crittografato sicuro',
    'checkout.orderComplete': 'Ordine Completato!',
    'checkout.orderComplete.desc': 'Grazie per il tuo acquisto. Riceverai una email di conferma a breve con informazioni di tracciamento.',
    'checkout.orderSummary': 'Riepilogo Ordine',
    'checkout.redirecting': 'Reindirizzamento alla home page...',
    
    // About Page
    'about.title': 'La Nostra Missione',
    'about.subtitle': 'Siamo dedicati a fornire prodotti premium di erbe per vaporizzare che supportano il benessere mentale attraverso miscele botaniche naturali basate su evidenze.',
    'about.quality.title': 'I Nostri Standard di Qualità',
    'about.quality.approach': 'Formulazione Basata su Evidenze',
    'about.quality.compliance': 'Il Nostro Impegno per la Conformità',
    'about.trust.lab': 'Testato in Laboratorio',
    'about.trust.verified': '21+ Verificato',
    'about.trust.coa': 'COA Disponibile',
    'about.trust.shipping': 'Spedizione Gratis $50+',
    'about.disclaimer': 'Non per uso da parte di minori. Evitare durante la gravidanza o l allattamento. Consultare un operatore sanitario prima dell uso se si hanno condizioni mediche o si assumono farmaci.',
    
    // Education Page
    'education.title': 'Centro Educativo',
    'education.subtitle': 'Impara la scienza dietro la vaporizzazione erboristica e il benessere',
    'education.intro.title': 'La Scienza della Vaporizzazione Erboristica',
    'education.intro.desc': 'Capire come la vaporizzazione preserva i composti benefici evitando la combustione.',
    'education.safety.title': 'Linee Guida Sicurezza e Uso',
    'education.safety.temperature.title': 'Controllo della Temperatura',
    'education.safety.temperature.desc': 'Temperature ottimali per diverse erbe ed effetti desiderati.',
    'education.safety.temperature.range': 'Range raccomandato: 160-204°C (320-400°F)',
    'education.safety.session.title': 'Gestione delle Sessioni',
    'education.safety.session.desc': 'Tempistica e dosaggio appropriati per benefici ottimali.',
    'education.safety.session.length': 'Sessione raccomandata: 5-15 minuti',
    'education.benefits.title': 'Benefici per la Salute',
    'education.benefits.anxiety.title': 'Sollievo dall Ansia',
    'education.benefits.anxiety.desc': 'Come alcune erbe possono aiutare a ridurre l ansia e promuovere la calma.',
    'education.benefits.sleep.title': 'Supporto per il Sonno',
    'education.benefits.sleep.desc': 'Alternative naturali per una migliore qualità del sonno.',
    'education.benefits.focus.title': 'Chiarezza Mentale',
    'education.benefits.focus.desc': 'Erbe che possono migliorare la concentrazione e la funzione cognitiva.',
    'education.research.title': 'Ricerca e Studi',
    'education.research.intro': 'Esplora l evidenza scientifica dietro il benessere erboristico.',
    
    // Contact Page
    'contact.title': 'Contattaci',
    'contact.subtitle': 'Hai domande? Siamo qui per aiutare. Raggiungi il nostro team di supporto.',
    'contact.form.title': 'Inviaci un messaggio',
    'contact.form.name': 'Nome',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Oggetto',
    'contact.form.message': 'Messaggio',
    'contact.form.selectSubject': 'Seleziona un oggetto...',
    'contact.form.productInquiry': 'Richiesta Prodotto',
    'contact.form.orderStatus': 'Stato Ordine',
    'contact.form.shipping': 'Domanda Spedizione',
    'contact.form.returns': 'Resi e Rimborsi',
    'contact.form.safety': 'Sicurezza e Uso',
    'contact.form.wholesale': 'Richiesta Ingrosso',
    'contact.form.other': 'Altro',
    'contact.form.send': 'Invia Messaggio',
    'contact.form.sending': 'Invio...',
    'contact.form.success': 'Messaggio inviato con successo!',
    'contact.form.success.desc': 'Grazie per averci contattato. Ti risponderemo entro 1-2 giorni lavorativi a',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Orari di Lavoro',
    'contact.info.location': 'Posizione',
    'contact.info.responseTime': 'Risposta entro 1-2 giorni lavorativi',
    'contact.info.weekdays': 'Lunedì - Venerdì',
    'contact.info.time': '9:00 - 18:00 CET',
    'contact.info.spain': 'Spagna',
    'contact.info.shipping': 'Spediamo in tutta la Spagna e l Europa (dove consentito)',
    'contact.faq.title': 'Domande Frequenti',
    'contact.faq.track': 'Come tracciare il mio ordine?',
    'contact.faq.track.desc': 'Riceverai un numero di tracciamento via email una volta che il tuo ordine viene spedito. Usa questo numero per tracciare il tuo pacco sul sito web del corriere. La maggior parte degli ordini arriva entro 3-5 giorni lavorativi.',
    'contact.faq.returns': 'Qual è la vostra politica di reso?',
    'contact.faq.returns.desc': 'Offriamo una garanzia di soddisfazione di 30 giorni sui prodotti non aperti. Se non sei soddisfatto, contattaci per un rimborso completo. I prodotti aperti non possono essere restituiti a causa delle normative di sicurezza.',
    'contact.faq.choose': 'Come scelgo il prodotto giusto?',
    'contact.faq.choose.desc': 'Sfoglia per categoria (Sollievo dall Ansia, Supporto per il Sonno, Focus e Chiarezza, ecc.) o consulta il nostro Centro Educativo per benefici dettagliati delle erbe. Inizia con le miscele base se sei nuovo alla vaporizzazione delle erbe.',
    'contact.faq.ship': 'Spedite nel mio stato?',
    'contact.faq.ship.desc': 'Spediamo nella maggior parte degli stati USA. Alcune restrizioni di spedizione possono applicarsi in base alle normative locali. La tua idoneità alla spedizione sarà confermata al checkout.',
    'contact.faq.lab': 'I vostri prodotti sono testati in laboratorio?',
    'contact.faq.lab.desc': 'Sì! Ogni lotto viene sottoposto a test di laboratorio di terze parti per purezza, potenza e contaminanti. Certificato di Analisi (COA) disponibile tramite codice QR sulla confezione del prodotto o su richiesta.',
    'contact.help.title': 'Hai Bisogno di Aiuto con Spedizioni o Resi?',
    'contact.help.desc': 'Il nostro team di servizio clienti è qui per assisterti con qualsiasi domanda su spedizioni o resi.',
    'contact.disclaimer': 'Solo per adulti di 21 anni e oltre. Non destinato a diagnosticare, trattare, curare o prevenire alcuna malattia.',
    
    // Footer
    'footer.about.title': 'MindVap',
    'footer.about.desc': 'Erbe premium per vaporizzare focalizzate su soluzioni naturali di benessere mentale. Qualità prima, formulazioni basate su evidenze.',
    'footer.shop.title': 'Negozio',
    'footer.shop.all': 'Tutti i Prodotti',
    'footer.shop.anxiety': 'Sollievo dall Ansia',
    'footer.shop.sleep': 'Supporto per il Sonno',
    'footer.shop.focus': 'Focus e Chiarezza',
    'footer.info.title': 'Informazioni',
    'footer.info.about': 'Chi Siamo',
    'footer.info.education': 'Centro Educativo',
    'footer.info.contact': 'Contatti',
    'footer.legal.title': 'Legale',
    'footer.legal.privacy': 'Informativa sulla Privacy',
    'footer.legal.terms': 'Termini di Servizio',
    'footer.legal.shipping': 'Spedizioni e Resi',
    'footer.disclaimer': 'Questo prodotto non è stato valutato dalla FDA e non è destinato a diagnosticare, trattare, curare o prevenire alcuna malattia. Non per uso da parte di minori. Evitare durante la gravidanza o l allattamento.',
    'footer.copyright': '© 2025 MindVap. Tutti i diritti riservati. Deve essere 21+ per acquistare.',
    'footer.trust.lab': 'Testato in Laboratorio',
    'footer.trust.shipping': 'Spedizione Gratis $50+',
    'footer.trust.verified': '21+ Verificato',
    'footer.trust.coa': 'COA Disponibile',
    
    // Age Gate
    'age.title': 'Verifica dell Età Richiesta',
    'age.subtitle': 'Devi avere 21 anni o più per entrare in questo sito.',
    'age.verify': 'Ho 21 anni o più',
    'age.enter': 'Entra nel Sito',
    'age.exit': 'Esci dal Sito',
    'age.error': 'Devi verificare di avere 21 anni di età o più per continuare.',
    
    // Error Messages
    'error.required': 'Questo campo è richiesto',
    'error.email': 'Per favore inserisci un indirizzo email valido',
    'error.minLength': 'Deve essere di almeno {min} caratteri',
    'error.maxLength': 'Non deve essere più di {max} caratteri',
    'error.ageVerification': 'Devi verificare di avere 21 anni di età o più per completare questo acquisto.',
    'error.fillFields': 'Per favore compila tutti i campi richiesti.',
    'error.network': 'Errore di rete. Per favore riprova.',
    'error.payment': 'Pagamento fallito. Per favore riprova.',
    'error.unknown': 'Si è verificato un errore inaspettato.',
    
    // Chat
    'chat.welcome': 'Ciao! Come possiamo aiutarti oggi?',
    'chat.quickReplies.trackOrder': 'Traccia il mio ordine',
    'chat.quickReplies.productQuestions': 'Domande sui prodotti',
    'chat.quickReplies.shippingInfo': 'Informazioni spedizione',
    'chat.quickReplies.other': 'Altro',
    'chat.quickReplies.contactSupport': 'Contatta supporto',
    'chat.header': 'Assistenza Clienti',
    'chat.inputPlaceholder': 'Scrivi il tuo messaggio...',
    'chat.speakToHuman': 'Parla con una persona',
    'chat.openAriaLabel': 'Apri assistenza chat',
    'chat.minimizeAriaLabel': 'Minimizza chat',
    'chat.closeAriaLabel': 'Chiudi chat',
    'chat.comingSoon': 'Funzionalità chat in arrivo!',
    // Chat Bot Responses
    'chat.response.orderTracking': 'Per favore fornisci il tuo numero di ordine e ti aiuteremo a rastrearlo. Puoi anche controllare lo stato del tuo ordine nella dashboard del tuo account.',
    'chat.response.shipping': 'Offriamo spedizione standard (5-7 giorni) e spedizione express (2-3 giorni). Spedizione gratuita su ordini superiori a $50 (€75 in Europa).',
    'chat.response.returns': 'La nostra politica di reso permette resi entro 30 giorni dall\'acquisto. Gli articoli devono essere in condizione originale. Contatta support@mindvap.com per istruzioni di reso.',
    'chat.response.payment': 'Accettiamo tutte le principali carte di credito in modo sicuro attraverso Stripe. Le tue informazioni di pagamento sono crittografate e protette.',
    'chat.response.product': 'Le nostre miscele di erbe sono accuratamente realizzate usando ingredienti premium. Ogni pagina del prodotto contiene informazioni dettagliate su ingredienti, benefici e uso.',
    'chat.response.ageVerification': 'Sì, devi avere 21 anni o più per acquistare i nostri prodotti di erbe. Questo è richiesto dalla legge e prendiamo sul serio la verifica dell\'età.',
    'chat.response.international': 'Sì, spediamo internazionalmente! Attualmente spediamo in oltre 30 paesi europei con tariffe di spedizione europee e calcoli IVA.',
    'chat.response.contact': 'Puoi contattare il nostro team di supporto a support@mindvap.com o attraverso questa chat. Típicamente rispondiamo entro 2-4 ore durante gli orari di lavoro.',
    'chat.response.pricing': 'I nostri prezzi variano per prodotto e quantità. Puoi trovare tutte le informazioni sui prezzi nelle nostre pagine prodotto. Offriamo tariffe competitive e spedizione gratuita su ordini superiori a $50.',
    'chat.response.fallback': 'Grazie per il tuo messaggio! Un agente di supporto risponderà a breve. Puoi anche inviarci un\'email a support@mindvap.com.',
    
    // Authentication - merged from auth.ts
    ...authTranslations.it
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to English
    const saved = localStorage.getItem('mindvap-language') as Language;
    return saved && ['en', 'es', 'it'].includes(saved) ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('mindvap-language', lang);
  };

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key; // Return key if translation not found
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};